[package]
name = "flavo_warthog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flavo_engine = { path = "../flavo_engine" } 
rand = "0.8.5"
